### ISSUE TITLE
Single Quotes in Markup Break Highlighting

### ISSUE THREAD

**Issue by pifantastic** [anvie/SoyTemplate#1]
A single quote in a block of markup will break syntax highlighting: ![Example](http://grimhappy.com/i/d27fd.png)

I'm not very familiar with TextMate .tmLanguage files, but that appears to be where Syntax Highlighting is defined.  If I get some time I will play around with it.

**Comment by anvie** [comment]
Hi pifantastic, thx for report, will fix it asap. :)

**Comment by anvie** [comment]
I just fix this issue, commit 60bb5f1e3c7cf4cd0546fc76bfd33b956cb26adc

thx for your report.

**Comment by pifantastic** [comment]
Thanks!
